### ISSUE TITLE
sometimes getting: "Invalid blinded output hex."

### ISSUE THREAD

**Issue by Kelbie** [KevinKelbie/zerolink-util#1]
"Invalid blinded output hex."
    2018-06-13 17:48:02 - Post Input(s) - <Response [400]>
    lines: 
    Exception in thread Thread-1:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
        self.run()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
        self._target(*self._args, **self._kwargs)
      File "../zerolink/client.py", line 110, in postConfirmation
        self.reference["uniqueId"],
    TypeError: string indices must be integers

Not sure what triggers it right now because it only sometimes throws this error.

**Comment by nopara73** [comment]
Apparently it's malformed hex:

https://github.com/zkSNACKs/WalletWasabi/blob/da65dd27f548044085a92b86380edbc84d7e97b5/WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs#L238-L246

**Comment by KevinKelbie** [comment]
Thanks @nopara73! 👍 

I added padding so that its a valid hex.

Fixed it with this commit: https://github.com/KevinKelbie/zerolink-util/commit/8b69461efe91a44e15793453ca8184bfbd3b7de8
